### ISSUE TITLE
How do you define a high symmetry path?

### ISSUE THREAD

**Issue by ham-radio-72** [Green-Phys/green-ac#1]
I compiled the code and couldn't figure out what flag to use to define the high symmetry path that I wish to do AC on.

**Comment by iskakoff** [comment]
symmetry path is defined in the initialization scripts from `green-mbtools`

**Comment by egull** [comment]
I guess the question is: does this need a more extensive description on the home page? If so, Ming, could you contribute one once you’ve made sense of it? Sergei can help you make sense of it.
